### PR TITLE
fix(call): leave call along with room

### LINKED ISSUE #32483: Leaving a room while there is an ongoing call in PIP mode will crash the app
### Steps to reproduce

1. Where are you starting? What can you see?

- Be in an active call in roomA
- Put the call in PIP mode
- Leave the room (the room the call is hapening to)

#### What did you expect?

The call get closed? Maybe a warning saying there is an ongoing call

#### What happened instead?

The app "crashes"

Image

### Operating system

_No response_

### Browser information

_No response_

### URL for webapp

_No response_

### Application version

_No response_

### Homeserver

_No response_

### Will you send logs?

Yes

### PR DESCRIPTION
**Pull request by defaultdino**
closes #32483

I have tested this locally in room calls and it behaves as expected (the call is disconnected, then room is left)

- Attempts to hang up legacy based calls when leaving a room
- Attempts to disconnect active widget based call when leaving a room
- Add two new test cases covering this in `leave-behaviour.ts`

## Checklist

- [X] I have read through [review guidelines](https://github.com/element-hq/element-web/blob/develop/docs/review.md) and [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md).
- ~~[ ] Tests written for new code (and old code if feasible).~~
- ~~[ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.~~
- [x] Linter and other CI checks pass.
- [X] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

### CODE REVIEW

File: apps/web/src/utils/leave-behaviour.ts [hunk 1]
```diff
@@ -59,6 +61,15 @@ export async function leaveRoomBehaviour(
         throw new Error(`Expected to find room for id ${roomId}`);
     }
 
+    const activeCall = CallStore.instance.getActiveCall(roomId);
+    if (activeCall) {
+        try {
+            await activeCall.disconnect();
+        } catch {
+            logger.warn("Failed to disconnect call before leaving room.");
```
Comment (t3chguy) [inline apps/web/src/utils/leave-behaviour.ts]: logging the error would be good

Comment (defaultdino) [reply apps/web/src/utils/leave-behaviour.ts]: My bad

File: apps/web/src/utils/leave-behaviour.ts [hunk 2]
```diff
@@ -59,6 +61,15 @@ export async function leaveRoomBehaviour(
         throw new Error(`Expected to find room for id ${roomId}`);
     }
 
+    const activeCall = CallStore.instance.getActiveCall(roomId);
+    if (activeCall) {
+        try {
+            await activeCall.disconnect();
+        } catch (e) {
+            logger.warn("Failed to disconnect call before leaving room: " + e);
```
Comment (t3chguy) [inline apps/web/src/utils/leave-behaviour.ts]:
```suggestion
            logger.warn("Failed to disconnect call before leaving room: ", e);
```

This passes the error to the console to render better

File: apps/web/src/utils/leave-behaviour.ts [hunk 3]
```diff
@@ -9,6 +9,7 @@ Please see LICENSE files in the repository root for full details.
 import { sleep } from "matrix-js-sdk/src/utils";
 import React, { type ReactNode } from "react";
 import { EventStatus, MatrixEventEvent, type Room, type MatrixClient, MatrixError } from "matrix-js-sdk/src/matrix";
+import { logger } from "@sentry/browser";
```
Comment (t3chguy) [inline apps/web/src/utils/leave-behaviour.ts]: ah, wrong logger import

**Review by t3chguy — COMMENTED** [review]
Your change needs some test coverage

**Comment by t3chguy** [comment]
https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md#:~:text=Please%20do%20not%20use%20force%20push%20in%20your%20PRs.%20Doing%20so%20means%20we%20can%27t%20see%20what%20has%20changed.%20We%20use%20squash%20merge%20to%20get%20a%20%22clean%22%20git%20history.

**Comment by defaultdino** [comment]
@t3chguy my bad. I had tried doing some stuff in the Call classes clean() function that was overkill and missed the force-push mention in the guidelines

File: apps/web/src/models/Call.ts [hunk 4]
```diff
@@ -953,6 +955,18 @@ export class ElementCall extends Call {
...
+        if (!this.connected || member.membership === KnownMembership.Join) return;
+        if (!this.participants.has(member)) return;
+
+        const joinedParticipants = [...this.participants.keys()].filter((p) => p.membership === KnownMembership.Join);
+        if (joinedParticipants.length <= 1) {
+            this.disconnect().catch((e) => {
+                logger.warn("Failed to auto-disconnect from empty call: ", e);
+            });
+        }
+    };
```
Comment (robintown) [inline apps/web/src/models/Call.ts]: This callback appears to be doing more than what the PR claims it is doing, could you please remove it? We don't want group calls to auto-hangup like this, and while we do want DM calls to auto-hangup, that functionality belongs in Element Call (where it is currently implemented).

**Review by t3chguy — APPROVED** [review]
Looks sane to me, thanks

**Review by robintown — CHANGES_REQUESTED** [review]

File: apps/web/src/utils/leave-behaviour.ts [hunk 5]
```diff
@@ -59,6 +62,19 @@ export async function leaveRoomBehaviour(
...
+
+    // hang up widget based calls
+    const activeCall = CallStore.instance.getActiveCall(roomId);
+    if (activeCall) {
+        try {
+            await activeCall.disconnect();
+        } catch (e) {
+            logger.warn("Failed to disconnect call before leaving room: ", e);
+        }
+    }
```
Comment (robintown) [inline apps/web/src/utils/leave-behaviour.ts:80]: Given that this is what's protecting the crash from happening, I imagine that if the `disconnect` call fails for any reason we would still hit the crash. I'm still willing to accept this change since it seems desirable to send a hangup event when leaving the room anyway, but just wanted to note that this isn't quite a complete fix for https://github.com/element-hq/element-web/issues/32483.

The root cause of the crash has to do with how PersistedElement works, which is something I've been intending to majorly refactor soon, so I would encourage you not to worry about it. :smiley:

File: apps/web/src/utils/leave-behaviour.ts [hunk 6]
```diff
@@ -59,6 +62,19 @@ export async function leaveRoomBehaviour(
         throw new Error(`Expected to find room for id ${roomId}`);
     }
 
+    // hang up legacy based calls
+    LegacyCallHandler.instance.hangupOrReject(roomId);
```
Comment (robintown) [inline apps/web/src/utils/leave-behaviour.ts]: This could go in a `try` block as well for good measure.

**Review by robintown — COMMENTED** [review]
I think this is a sensible change even if it is not a complete fix for the linked issue.

**Comment by defaultdino** [comment]
@robintown Thanks! fixed

**Review by robintown — APPROVED** [review]
