### PR TITLE
Block change recovery key button while a change is ongoing.

### LINKED ISSUE #30662: Clicking "Confirm new recovery key" multiple times leaves 4S in a mess
### Steps to reproduce

1. Settings -> Encryption -> Change recovery key
2. Copy recovery key, press "Continue"
3. Paste recovery key
   Image
4. Press "Confirm new recovery key"
5. Nothing happens initially. Did it work? Who knows.
6. Press it lots more times

#### What did you expect?

4S successfully changed

#### What happened instead?

Image

and

Image

(possibly multiple iterations of those two, depending how many key change requests you managed to queue up)

and

Image

### Operating system

_No response_

### Application version

_No response_

### How did you install the app?

_No response_

### Homeserver

_No response_

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #30662

This changes `<KeyForm>` to block multiple changes until the promise from `onSubmit` has concluded.

~~This still probably needs a test change to make sure we disable the button.~~

## Checklist

- [ ] I have read through [review guidelines](../docs/review.md) and [CONTRIBUTING.md](../CONTRIBUTING.md).
- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

### CODE REVIEW

File: test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx [hunk 1]
```diff
@@ -120,27 +122,66 @@ describe("<ChangeRecoveryKey />", () => {
...
+               expect(finishButton).not.toBeDisabled();
+            });
+
+            jest.spyOn(Modal, "createDialog");
+
             await user.click(finishButton);
 
-            await screen.findByText("Failed to set up secret storage");
-            await screen.findByText("Error: can't bootstrap");
+            expect(Modal.createDialog).toHaveBeenCalledWith(ErrorDialog, {
```
Comment (Half-Shot) [inline test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx:146]: @andybalaam Noting this change. This test was causing an ErrorDialog to popup and that was apparently persisting to the next test. Other tests seem to mock out createDialog for this sort of error testing, so I suppose it's been encountered before.

Anyway, this seemed to make it all work.

File: test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx [hunk 2]
```diff
@@ -120,27 +122,66 @@ describe("<ChangeRecoveryKey />", () => {
...
+
+            const finishButton = getByRole("button", { name: "Finish set up" });
+            const input = getByTitle("Enter recovery key");
+            await userEvent.type(input, "encoded private key");
+
+            await waitFor(() => {
+               expect(finishButton).not.toBeDisabled();
+            });
+
+            await user.click(finishButton);
```
Comment (andybalaam) [inline test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx:182]: Should we do this multiple times? (How are we checking it disallows repeated attempts?)

**Review by andybalaam — CHANGES_REQUESTED** [review]
Looking good; one question about the test.

**Comment by andybalaam** [comment]
I tested it and it seems to work :tada:

File: test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx (hunk 2 above)
Comment (Half-Shot) [reply test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx:182]: What??? There were 3 button presses here. Sorry, I must have eaten them
