### PR TITLE
Revert `GoToHome` keyboard shortcut to `Ctrl`–`Shift`–`H` on macOS

### LINKED ISSUE #28576: `Cmd`–`Shift`–`H` keyboard shortcut hijacks the Safari shortcut for Home
### Steps to reproduce

1. Open a room
2. Press `Cmd`–`Shift`–`H`

#### What did you expect?

Safari goes to the Home page set in its Settings.

#### What happened instead?

Hidden events become visible.

I think that Element shouldn't hijack a Safari keyboard shortcut like this one because it serves a different purpose.

Similar issue: #14381
Older counter-issue: #19850
Same issue in another repo: https://github.com/openstreetmap/iD/issues/10479

### Operating system

macOS `15.3.1`

### Browser information

Safari `18.3`

### URL for webapp

https://develop.element.io/

### Application version

Element `0997e0a747f7-js-d81929de4c95` (`1.11.93`+)

### Homeserver

https://riot.grin.hu/

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by gy-mate**
Fixes #28576 by partially reverting https://github.com/matrix-org/matrix-react-sdk/pull/7631/

## Checklist

- [x] ~~Tests written for new code (and old code if feasible).~~ N/A
- [x] ~~New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.~~ N/A
- [x] Linter and other CI checks pass.
  - _Pull Request / action / Preview Changelog (pull_request_target)_ seems to fail only due to a missing label that I can't add.
- [x] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/element-web)

### CODE REVIEW

**Comment by florianduros** [comment]
Hi,

The issue is specific to safari and the fix will remove the shortcut all the others browsers on Macos (firefox, chrome...).

**Comment by gy-mate** [comment]
> the fix will remove the shortcut all the others browsers on Macos (firefox, chrome...)

@florianduros Why is that? I just wanted to _change_ the shortcut to `Ctrl`–`Alt`–`H`.

File: src/accessibility/KeyboardShortcuts.ts [hunk 1]
```diff
@@ -520,7 +520,7 @@ export const KEYBOARD_SHORTCUTS: IKeyboardShortcuts = {
     },
     [KeyBindingAction.GoToHome]: {
         default: {
-            ctrlOrCmdKey: true,
+            ctrlKey: true,
```
Comment (florianduros) [inline src/accessibility/KeyboardShortcuts.ts:523]: This goes against the PR description, this is not `Ctrl–Alt–H`.

**Review by florianduros — CHANGES_REQUESTED** [review]
Hi sorry for the delay

File: src/accessibility/KeyboardShortcuts.ts (hunk 1 above)
Comment (gy-mate) [reply src/accessibility/KeyboardShortcuts.ts:523]: My bad—I've corrected the title of the PR! I hope it's okay now.

**Review by florianduros — APPROVED** [review]
Tested and it works, thanks for the contribution
