### PR TITLE
Fix local room encryption status always not enabled

### LINKED ISSUE #28774: `End-to-end encryption isn't enabled` while starting a private chat
### Steps to reproduce

1. Where are you starting? What can you see?
I'm starting a new private conversation with the Test Person.

2. What do you click?
I click the name, and then the chat window opens.

3. I see the following message:
```
End-to-end encryption isn't enabled
Your private messages are normally encrypted, but this room isn't. Usually this is due to an unsupported device or method being used, like email invites.
```
Screenshot 2024-12-19 at 09 49 07

#### What did you expect?
As I understand it, this message appears because the conversation hasn't started **yet**, so the encryption keys haven't been exchanged. The problem is that users may not know if encryption will be established after the first message or not.

Is there any chance to change this information or remove it before the conversation starts?
That would be very helpful.

### Operating system

macOS

### Browser information

Chrome Version 131.0.6778.140 (Official Build) (arm64)

### URL for webapp

_No response_

### Application version

v1.11.88

### Homeserver

v1.121.1

### Will you send logs?

No

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #28774

| Before  | After |
| ------------- | ------------- |
| image| image |

### CODE REVIEW

File: src/hooks/useIsEncrypted.ts [hunk 1]
```diff
@@ -7,9 +7,29 @@ Please see LICENSE files in the repository root for full details.
...
+ * If the room is a LocalRoom, check the state directly.
+ * Otherwise, use the crypto API to check if encryption is enabled in the room.
+ *
+ * @param room - The room to check.
+ * @param cryptoApi - The crypto API from the Matrix client.
+ */
+export async function isRoomEncrypted(room: Room, cryptoApi: CryptoApi): Promise<boolean> {
+    if (room instanceof LocalRoom) {
+        // For local room check the state.
+        // The crypto check fails because the eventId is not valid (it is a local id)
```
Comment (andybalaam) [inline src/hooks/useIsEncrypted.ts]: Do you mean "room ID" instead of "eventId"?

File: src/models/LocalRoom.ts [hunk 2]
```diff
@@ -50,4 +57,18 @@ export class LocalRoom extends Room {
     public get isError(): boolean {
         return this.state === LocalRoomState.ERROR;
     }
+
+    /**
+     * Check if encryption is enabled in this room.
+     * True if the room has any encryption state event
+     */
+    public isEncryptionEnabled(): boolean {
```
Comment (andybalaam) [inline src/models/LocalRoom.ts:65]: It would be great to have a couple of unit tests for this function.

File: src/models/LocalRoom.ts [hunk 3]
```diff
@@ -50,4 +57,18 @@ export class LocalRoom extends Room {
...
+        // check the local room state
+        const encryptionState = this.getLiveTimeline()
+            .getState(Direction.Forward)
+            ?.getStateEvents(EventType.RoomEncryption)[0];
```
Comment (andybalaam) [inline src/models/LocalRoom.ts]: This feels a little messy - is there a nicer way? E.g. is asking whether the length of the returned list is `>0`.

This is a soft suggestion: if you prefer this way of doing it I can live with it :-)

File: src/hooks/useIsEncrypted.ts (hunk 1 above)
Comment (florianduros) [reply src/hooks/useIsEncrypted.ts]: I suppose it's eventId, @BillCarsonFr ?

File: src/models/LocalRoom.ts (hunk 2 above)
Comment (florianduros) [reply src/models/LocalRoom.ts:65]: https://github.com/element-hq/element-web/pull/30461/commits/7b6c27700a6bb285648e973469cd5b04a0143b2a

File: src/models/LocalRoom.ts (hunk 3 above)
Comment (florianduros) [reply src/models/LocalRoom.ts]: https://github.com/element-hq/element-web/pull/30461/commits/94bb6f096fc2cd4a849df01e81e22181a363c82b

File: src/hooks/useIsEncrypted.ts (hunk 1 above)
Comment (BillCarsonFr) [reply src/hooks/useIsEncrypted.ts]: mmm right, I thought it was the eventId causing the problem `"event_id": "~local+m1754055435475.90:m1754055435486.92",` 
but actually it fails before when trying to do `new RustSdkCryptoJs.RoomId(roomId),` in `isEncryptionEnabledInRoom`

Comment (florianduros) [reply src/hooks/useIsEncrypted.ts]: https://github.com/element-hq/element-web/pull/30461/commits/da32bbca2f04c855a27b6ea2578e02c06d1dd0e3
