### PR TITLE
Catch errors after syncing recovery

### LINKED ISSUE #29229: EW: Inform users when fixing "key storage out of sync" fails
**Problem**

In case the user is notified about their _key storage is out of sync_ (their device is missing a secret), they have the option to enter their recovery key and try to fix the issue by retrieving the missing secret from key storage. However, it could happen that the key storage also does not have the secret so the user will remain in the _key storage is out of sync_ broken state.

The issue is that currently the user is not informed at all that fixing the issue failed, and that they need to reset their identity to set it up correctly.

**Designs**
* Inform user that they [need to do a reset](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=2614-28144&t=735WZ7iFS1LHv6nM-4).

Note that the designs of the entire _key storage is out of sync_ journey assume that the recovery key entry modal is [modernized](https://github.com/element-hq/element-meta/issues/2722) and the entire flow is embedded into the Settings overlay. This would be desired, but it is acceptable if the recovery key entry is present as modal after which user lands in the Settings overlay where they are told about the need to reset.

### PR DESCRIPTION
**Pull request by andybalaam**
Fixes #29229

### CODE REVIEW

File: src/components/views/settings/encryption/ResetIdentityPanel.tsx [hunk 1]
```diff
@@ -35,11 +35,16 @@ interface ResetIdentityPanelProps {
      * "compromised" is shown when the user chooses 'reset' explicitly in settings, usually because they believe their
      * identity has been compromised.
      *
+     * "sync_failed" is shown when the user tried to recover their identity but the process failed, probably because
+     * the required information is missing from recovery.
+     *
      * "forgot" is shown when the user has just forgotten their passphrase.
```
Comment (richvdh) [inline src/components/views/settings/encryption/ResetIdentityPanel.tsx:41]: feels like maybe this documentation belongs next to the definition of `ResetIdentityPanelVariant` now, but :man_shrugging:

**Review by richvdh — APPROVED** [review]
Looks good. Would there be any chance of a playwright test to assert that this works when it's all plugged together?

**Comment by andybalaam** [comment]
Argh, sorry I forgot to rebase before merging.

**Comment by andybalaam** [comment]
Ah, no I see that it was squashed so it's not quite so bad.
